---
title: "Untitled"
output: html_document

---


```{r}
setwd("C:/OneDrive/7_DataScience/02_Visual Studio/2_GitHub/Portfolio_Analytics/Portfolio_Analytics")
library(openxlsx)
### ERROR no zip installed:
#library(devtools)
#t=find_rtools()
#Sys.setenv(R_ZIPCMD = "C:/RBuildTools/3.4/bin/zip")
#### SOLVED

Sys.setenv(R_ZIPCMD = "C:/RBuildTools/3.4/bin/zip")
wb <- loadWorkbook(file = "OrderBook.xlsx")
#writeData(wb, sheet = 1, x = iris, name = "iris3", startCol = 10)
Order_complete <- read.xlsx("OrderBook.xlsx", namedRegion = "Order", detectDates = T)




Order_complete$TimeStamp = as.POSIXct(Order_complete$TimeStamp)


i = 1
Order = Order_complete[i,]
Order$OrderType
Order$TimeStamp
Order$Feature1
Order$Feature2
OrderDate="2017-11-03"
OrderFeature1 = Order[1, 7]
OrderFeature2 = Order[1, 4]
Ticker=Order$Symbol_short



```

## Get intraday data from Alpha Vantage

```{r}
## Source Telegram API
source("R:/7_DataScience/01_R/12_AlphaVantage/alpha_key.R")
## Get data 
QuoteAV<- av_get(symbol = Ticker, av_fun = "TIME_SERIES_INTRADAY", interval = "5min", outputsize = "full")
```
You can also embed plots, for example:

```{r, echo=FALSE}
### PREP
library(quantmod)
library(dplyr)
library(plotly)

#getSymbols("AAPL", src = 'yahoo')
#df <- data.frame(Date = index(AAPL), coredata(AAPL))
#df <- tail(df, 30)


#######
#######  CHOOSE
############################################

        #df_plotx <- filter(Quotes, symbol == "2PP.F",date>="2017-11-01")
         df_plotx = QuoteAV
#############################################
#Check
tail(df_plotx)


```

```{r}




trigger = Order$Feature2
    
(triggerDate=df_plotx$timestamp[which(df_plotx$high > trigger)])
triggerDate[1]



triggerStates = df_plotx[which(df_plotx$high > trigger),]






Execution <- df_plotx[which(trigger > df_plotx$low),]
ExecutionFlag = nrow(Execution) != 0
ExecutionFlag



NewTrigger = max(triggerStates$high) * (1 - Order$Feature1[i])

### add new order
library(dplyr)
New <- Order_complete[i,]
New$Feature2 = NewTrigger
New$TimeStamp = df_plotx[max(triggerStates$high),]$timestamp

Order=bind_rows(Order_complete, New)
Order
#################
#save to xlsx
#removeTable(wb, 1, "Table1")

writeData(wb,1,Order, startCol = "B", startRow = 2)

saveWorkbook(wb, file = "OrderBook.xlsx", overwrite = TRUE)
#############3
```




```{r}

###########################
##PREP
time = c(as.POSIXct(Order$TimeStamp), tail(df_plotx$timestamp, n = 1))

trigger = c(Order$Feature2, tail(Order$Feature2, n = 1))
###############

#######################3
# cutom colors
i <- list(line = list(color = '#FFD700'))
d <- list(line = list(color = '#0000ff'))
###########################

minDate=min(QuoteAV$timestamp)
minDate

# annotation
a <- list(text = "Stock Split",
          x = triggerDate[1],
          y = 1.02,
          xref = 'x',
          yref = 'paper',
          xanchor = 'left',
          showarrow = FALSE
          )

# use shapes to create a line
l <- list(type = line,
          x0 = triggerDate[1]+3600,
          x1 = triggerDate[1] + 3600,
          y0 = 0,
          y1 = 1,
          xref = 'x',
          yref = 'paper',
          line = list(color = 'black',
                      width = 0.5)
          )


          
p <- df_plotx %>%
    plot_ly(x = ~timestamp, type = "ohlc",
          open = ~open, close = ~close,
          high = ~high, low = ~low
          ##############33
          #custom colors
          ,increasing = i, decreasing = d
          ###############3
          ) %>%
          layout(title = "Custom Colors"
          ,
         annotations = a,
         shapes = l
         
         ) %>%
         add_lines(x = time, y = trigger, name = "hv", line = list(shape = "hv"))
p



################
#Save plotly:

### PhantomJS needed
### webshot needed
export(p, file = "image.jpeg")
#You can even change the file type of output by selecting the extension as .png, jpeg or .pdf.
#You can also save the image in html file which allows you the plotly experience like zooming or showing annotations by using htmlwidgets::saveWidget:


htmlwidgets::saveWidget(p, file = "image.html")


```

```{r}
if (ExecutionFlag == T) {
    


        ##Source Telegram API
        source("R:/7_DataScience/01_R/11_Telegram/telegram_botDR.R")

        ## Create Message
            ############
            text = triggerStates


            library(DT)
            d = datatable(iris)
            library(gridExtra)
            png("table.png")
            d <- tableGrob(triggerStates)
            grid.arrange(d)
            dev.off()


        text = paste("Order executed on", triggerDate)
        ############


        ## Send some messages..

            bot$sendMessage(text)

            #Image = "table.png"
            Image = "image.jpeg"
            bot$sendPhoto(Image, caption = 'This is my awesome graph')
}
```

```{r}
library(plotly)

x <- c(1:5)
y <- c(1, 3, 2, 3, 1)

d <- plot_ly(x = ~x) %>%
    add_lines(y = ~y, name = "linear", line = list(shape = "linear")) %>%
    add_lines(y = y + 5, name = "spline", line = list(shape = "spline")) %>%
    add_lines(y = y + 10, name = "vhv", line = list(shape = "vhv")) %>%
    add_lines(y = y + 15, name = "hvh", line = list(shape = "hvh")) %>%
    add_lines(y = y + 20, name = "vh", line = list(shape = "vh")) %>%
    add_lines(y = y + 25, name = "hv", line = list(shape = "hv"))
  d
```


