---
title: "Untitled"
output: pdf_document
---


# Load packages

```{r}
library(dplyr)
library(tidyquant)
```




```{r}
AllocationCurrent = read.table("AllocationCurrent.csv", sep = ",")

ticker <- as.vector(AllocationCurrent$Symbol)
From = "2014-01-01"
To = "2017-08-20"

```

Get stock prices

```{r}

stock_prices <- ticker %>%
    tq_get(get = "stock.prices",
           from = From,
           to = To)
stock_prices

Ra <- stock_prices %>%
    group_by(symbol) %>%
    tq_transmute(select = adjusted,
                 mutate_fun = periodReturn,
                 period = "monthly",
                 col_rename = "Ra")



```




```{r}
Rb <- "^GDAXI" %>%
    tq_get(get  = "stock.prices",
           from = From,
           to   = To) %>%
    tq_transmute(select     = adjusted, 
                 mutate_fun = periodReturn, 
                 period     = "monthly", 
                 col_rename = "Rb")



RaRb <- left_join(Ra, Rb, by = c("date" = "date"))
RaRb

RaRb_capm <- RaRb %>%
    tq_performance(Ra = Ra,
                   Rb = Rb, 
                   performance_fun = table.CAPM)
RaRb_capm

AB=RaRb_capm %>%
    select(Alpha, Beta)
```


```{r}
args(SharpeRatio)

SR=stock_returns_monthly %>%
    tq_performance(Ra = Ra,
                   Rb = NULL,
                   performance_fun = SharpeRatio)



# Now we have the Sharpe Ratio for each of the stocks. 
#What if we want to adjust the parameters of the function? 
#We can just add on the arguments of the underlying function.

SR_2=stock_returns_monthly %>%
    tq_performance(Ra = Ra, 
                   Rb = NULL, 
                   performance_fun = SharpeRatio, 
                   Rf = 0.03 / 12, 
                   p = 0.99)
```






## Portfolios



```{r}

#1B & 2B
#baseline_returns_monthly <- "XLK" %>%
    #tq_get(get  = "stock.prices",
           #from = "2010-01-01",
           #to   = "2015-12-31") %>%
    #tq_transmute(select     = adjusted, 
                 #mutate_fun = periodReturn, 
                 #period     = "monthly", 
                 #col_rename = "Rb")
baseline_returns_monthly =Rb


#3A Method 2

wts_map <- tibble(
    symbols = c(ticker[1:2]),
    weights = c(0.5, 0.5)
)
wts_map

Ra <- stock_returns_monthly %>%
    tq_portfolio(assets_col  = symbol, 
                 returns_col = Ra, 
                 weights     = wts_map, 
                 col_rename  = "Ra")

#3B: Merging Ra and Rb

RaRb_single_portfolio <- left_join(Ra, 
                                   baseline_returns_monthly,
                                   by = "date")
RaRb_single_portfolio


### Ignores NA
#RaRb_single_portfolio[27,3]=0

########################################## ERROR
####### Solution Naming of Ra has to be column name in RaRb_single_portfolio
#4: Computing statistic
CAPM=RaRb_single_portfolio %>%
    tq_performance(Ra = Ra, Rb = Rb, performance_fun = table.CAPM)
CAPM
```

